# Generated by Django 4.1.7 on 2023-03-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
