# Generated by Django 4.1.7 on 2023-03-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_department_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('reg_no', models.CharField(max_length=10, unique=True)),
                ('roll', models.CharField(max_length=10, null=True)),
                ('session', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=50, null=True)),
                ('fathers_name', models.CharField(max_length=30, null=True)),
                ('mothers_name', models.CharField(max_length=30, null=True)),
                ('guardian_phone', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
