# Generated by Django 4.1.7 on 2023-03-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_department_description_student_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='rank',
            field=models.CharField(choices=[('Assistant Professor', 'Assistant Professor'), ('Professor', 'Professor'), ('Head of The Department', 'Head of The Department')], max_length=40, null=True),
        ),
    ]
