# Generated by Django 4.1.7 on 2023-03-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_teacher_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
