# Generated by Django 4.1.7 on 2023-03-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_teacher_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='rank',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='rank',
            field=models.CharField(choices=[('Lecturer', 'Lecturer'), ('Assistant Professor', 'Assistant Professor'), ('Professor', 'Professor'), ('Head of The Department', 'Head of The Department')], max_length=40, null=True),
        ),
    ]
