# Generated by Django 4.1.7 on 2023-03-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_student_description_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='rank',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
