# Generated by Django 4.1.7 on 2023-03-26 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_student_reg_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hsc_reg',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='hsc_roll',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.department'),
        ),
    ]
