# Generated by Django 4.1.7 on 2023-03-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_alter_student_hsc_roll_alter_student_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hsc_reg',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='hsc_roll',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
