# Generated by Django 4.1.7 on 2023-03-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_department_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accecpted', 'Accecpted')], default='Pending', max_length=40, null=True),
        ),
    ]
